import { z } from "zod";
import { HostfullyApi } from "./HostfullyApi";
import { Property } from "./PropertiesApi";

export const AmenityIdSchema = z.enum([
  "HAS_TV",
  "HAS_CABLE_TV",
  "HAS_SMART_TV",
  "HAS_AIR_CONDITIONING",
  "HAS_HEATING",
  "HAS_KITCHEN",
  "HAS_KITCHENETTE",
  "HAS_INTERNET_WIFI",
  "HAS_PAID_WIFI",
  "HAS_WIFI_SPEED_25",
  "HAS_WIFI_SPEED_50",
  "HAS_WIFI_SPEED_100",
  "HAS_WIFI_SPEED_250",
  "HAS_WIFI_SPEED_500",
  "HAS_WASHER",
  "HAS_DRYER",
  "HAS_SHARED_WASHER",
  "HAS_SHARED_DRYER",
  "HAS_POOL",
  "HAS_POOL_ALL_YEAR",
  "HAS_POOL_SEASONAL",
  "HAS_COMMUNAL_POOL",
  "HAS_HEATED_POOL",
  "HAS_INDOOR_POOL",
  "HAS_INDOOR_POOL_ALL_YEAR",
  "HAS_INDOOR_POOL_SEASONAL",
  "HAS_FENCED_POOL",
  "HAS_FENCED_YARD",
  "HAS_HOT_TUB",
  "HAS_FREE_PARKING",
  "HAS_FREE_STREET_PARKING",
  "HAS_PAID_OFF_PREMISES_PARKING",
  "HAS_PAID_ON_PREMISES_PARKING",
  "HAS_EV_CAR_CHARGER",
  "HAS_INDOOR_FIREPLACE",
  "IS_WHEELCHAIR_ACCESSIBLE",
  "HAS_SINGLE_LEVEL",
  "HAS_SMOKE_DETECTOR",
  "HAS_FIRE_EXTINGUISHER",
  "HAS_EMERGENCY_EXIT",
  "HAS_DEADBOLT_LOCK",
  "HAS_OUTDOOR_LIGHTING",
  "HAS_ESSENTIALS",
  "HAS_BALCONY_TERRASSE",
  "HAS_BABY_HIGH_CHAIR",
  "HAS_BABY_TRAVEL_BED",
  "HAS_CDDVD_PLAYER",
  "HAS_BOARD_GAMES",
  "HAS_BARBECUE",
  "HAS_ELEVATOR",
  "HAS_DEHUMIDIFIER",
  "HAS_CEILING_FAN",
  "HAS_VENTILATION_FAN",
  "HAS_HAIR_DRYER",
  "HAS_CROCKERY_CUTLERY",
  "HAS_POTS_PANS",
  "HAS_OVEN",
  "HAS_MICROWAVE_OVEN",
  "HAS_WATER_KETTLE",
  "HAS_COFFEE_MAKER",
  "HAS_DISHWASHER",
  "HAS_TOASTER",
  "HAS_FRIDGE",
  "HAS_KITCHEN_ISLAND",
  "HAS_DINING_TABLE",
  "HAS_ALARM_SYSTEM",
  "HAS_BASKETBALL_COURT",
  "HAS_CINEMA_ROOM",
  "HAS_GATED_PROPERTY",
  "HAS_HELIPAD",
  "HAS_GYM",
  "HAS_IPOD_STATION",
  "HAS_JACUZZI",
  "HAS_STEAM_ROOM",
  "HAS_LIBRARY",
  "HAS_MASSAGE_ROOM",
  "HAS_OFFICE",
  "HAS_DESK",
  "HAS_DESK_CHAIR",
  "HAS_COMPUTER_MONITOR",
  "HAS_PRINTER",
  "HAS_POOL_TABLE",
  "HAS_PIANO",
  "HAS_SAFE_BOX",
  "HAS_CABINET_LOCKS",
  "HAS_SEA_VIEW",
  "HAS_SMART_HOME",
  "HAS_SOCCER_FIELD",
  "HAS_TENNIS",
  "HAS_TOILETRIES",
  "HAS_WINE_CELLAR",
  "HAS_WARDROBE",
  "HAS_IRON",
  "HAS_IRONING_FACILITIES",
  "HAS_SHAMPOO",
  "HAS_BREAKFAST",
  "HAS_MEAL_DELIVERY",
  "HAS_BUZZER",
  "HAS_DOORMAN",
  "HAS_CARBON_MONOXIDE_DETECTOR",
  "HAS_FIRST_AID_KIT",
  "HAS_CAT",
  "HAS_DOG",
  "HAS_OTHER_PET",
  "HAS_24_CHECKIN",
  "HAS_SAFETY_CARD",
  "HAS_HANGERS",
  "IS_LAPTOP_FRIENDLY",
  "HAS_LOCK_ON_BEDROOM",
  "HAS_PRIVATE_ENTRANCE",
  "HAS_BABY_BATH",
  "HAS_BABY_MONITOR",
  "HAS_BABYSITTER_RECOMMENDATIONS",
  "HAS_BATHTUB",
  "HAS_CHANGING_TABLE",
  "HAS_CHILDRENS_BOOKS_AND_TOYS",
  "HAS_OUTDOOR_PLAY_AREA",
  "HAS_CHILDRENS_DINNERWARE",
  "HAS_CHILDCARE",
  "HAS_FIREPLACE_GUARDS",
  "HAS_GAME_CONSOLE",
  "HAS_OUTLET_COVERS",
  "HAS_PACK_N_PLAY_TRAVEL_CRIB",
  "HAS_ROOM_DARKENING_SHADES",
  "HAS_STAIR_GATES",
  "HAS_TABLE_CORNER_GUARDS",
  "HAS_WINDOW_GUARDS",
  "HAS_LAKE_ACCESS",
  "HAS_BEACH_FRONT",
  "HAS_WATER_FRONT",
  "HAS_SKI_IN_SKI_OUT",
  "HAS_STOVE",
  "CHECK_IN_OPTION",
  "CHECK_IN_OPTION_INSTRUCTION",
  "HAS_LINENS",
  "HAS_TOWELS",
  "HAS_HOT_WATER",
  "HAS_COOKING_BASICS",
  "HAS_SURVEILLANCE",
  "HAS_GARDEN",
  "HAS_DECK_PATIO",
  "HAS_AIR_FILTER",
  "HAS_ENHANCED_CLEANING",
  "HAS_CLEANING_WITH_DISINFECTANTS",
  "HAS_HIGH_TOUCH_SURFACES_CLEANING_WITH_DISINFECTANTS",
  "HAS_IN_PERSON_CHECKIN",
  "HAS_CONTACTLESS_CHECKIN",
  "HAS_CONCIERGE",
  "HAS_OCEAN_FRONT",
  "IS_RESORT",
  "IS_RURAL",
  "HAS_TOWN",
  "HAS_WATER_VIEW",
  "IS_DOWNTOWN",
  "HAS_GOLF_COURSE_VIEW",
  "IS_LAKEFRONT",
  "HAS_MOUNTAIN",
  "IS_NEAR_OCEAN",
  "HAS_RIVER",
  "HAS_VILLAGE",
  "HAS_BEACH",
  "HAS_BEACH_VIEW",
  "IS_GOLF_COURSE_FRONT",
  "HAS_LAKE",
  "HAS_LAKE_VIEW",
  "HAS_MOUNTAIN_VIEW",
  "HAS_BAKING_SHEET",
  "HAS_BARBEQUE_UTENSILS",
  "HAS_BEACH_ESSENTIALS",
  "HAS_BIDET",
  "HAS_BIKES_FOR_RENT",
  "HAS_BLENDER",
  "HAS_BOAT_SLIP",
  "HAS_BODY_SOAP",
  "HAS_BREAD_MAKER",
  "HAS_CLEANING_PRODUCTS",
  "HAS_CLOTHES_DRYING_RACK",
  "HAS_COFFEE",
  "HAS_CONDITIONER",
  "HAS_ETHERNET_CONNECTION",
  "HAS_EXERCISE_EQUIPMENT",
  "HAS_EXTRA_PILLOWS_AND_BLANKETS",
  "HAS_FIRE_PIT",
  "HAS_FREEZER",
  "HAS_HAMMOCK",
  "HAS_LAUNDROMAT_NEARBY",
  "HAS_KAYAK",
  "HAS_MINI_FRIDGE",
  "HAS_MOSQUITO_NET",
  "HAS_OUTDOOR_KITCHEN",
  "HAS_OUTDOOR_SEATING",
  "HAS_PING_PONG_TABLE",
  "HAS_POCKET_WIFI",
  "HAS_PORTABLE_FANS",
  "HAS_RAIN_SHOWER",
  "HAS_RECORD_PLAYER",
  "HAS_RESORT_ACCESS",
  "HAS_RICE_MAKER",
  "HAS_SAFE",
  "HAS_SHOWER_GEL",
  "HAS_SOUND_SYSTEM",
  "HAS_TRASH_COMPACTER",
  "HAS_WINE_GLASSES",
  "INVOICE_PROVIDED",
]);

const AmenitySchema = z.object({
  uid: z.string(),
  amenity: AmenityIdSchema,
  category: z.enum(["INDOOR", "OUTDOOR", "EXTRAS", "FAMILY"]).nullable(),
  propertyUid: z.string(),
  description: z.string().nullable(),
});

export type Amenity = z.infer<typeof AmenitySchema>;
export type AmenityId = z.infer<typeof AmenityIdSchema>;

export class AmenitiesApi {
  constructor(private readonly api: HostfullyApi) {}

  async getForProperty(property: Property) {
    return (
      await this.api.transport.fetch({
        path: `/api/v3.2/amenities`,
        query: { propertyUid: property.uid },
        method: "GET",
        response: z.object({
          amenities: z.array(AmenitySchema),
          _metadata: z.object({
            count: z.number(),
            totalCount: z.number().nullable(),
          }),
        }),
      })
    ).amenities;
  }

  async addToProperty(
    property: Property,
    { amenity, description }: { amenity: AmenityId; description?: string },
  ) {
    await this.api.transport.fetch({
      method: "POST",
      path: "/api/v3.2/amenities",
      body: {
        amenity,
        propertyUid: property.uid,
        description,
      },
      response: z.unknown(),
    });
  }

  async removeFromProperty(amenity: Amenity) {
    await this.api.transport.fetch({
      method: "DELETE",
      path: `/api/v3.2/amenities/${amenity.uid}`,
      response: z.unknown(),
    });
  }
}
